# Generated by Django 4.2.4 on 2023-09-03 08:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExternalTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=0, max_digits=100)),
                ("user_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "type",
                    models.IntegerField(choices=[(1, "Deposit"), (2, "Withdrawal")]),
                ),
                ("created_at", models.DateTimeField()),
                ("wallet_id", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=0, max_digits=100)),
                ("user_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "type",
                    models.IntegerField(choices=[(1, "Deposit"), (2, "Withdrawal")]),
                ),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
